package com.deathstar.vader.repository;

import static org.assertj.core.api.Assertions.assertThat;

import com.deathstar.vader.domain.Todo;
import java.util.List;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * Integration test against the database boundary. Rejecting H2! Start a real PostgreSQL 16 via
 * Testcontainers to ensure 100% consistent dialect and indexing behavior.
 */
@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Testcontainers
class TodoRepositoryTest {

    @Container @ServiceConnection
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    @Autowired private TodoRepository repository;

    @Test
    void shouldReturnTodosOrderedByCreatedAtDescending() throws InterruptedException {
        // 1. Prepare test data
        var todo1 = repository.save(new Todo("First Objective"));
        // Ensure micro-differences in timestamps
        Thread.sleep(10);
        var todo2 = repository.save(new Todo("Second Objective"));

        // 2. Execute query
        List<Todo> results = repository.findAllByOrderByCreatedAtDesc();

        // 3. Verify results (ensure the most recently created is at the top)
        assertThat(results).hasSize(2);
        assertThat(results.get(0).getTitle()).isEqualTo("Second Objective");
        assertThat(results.get(1).getTitle()).isEqualTo("First Objective");

        // Verify UUID was successfully generated by Hibernate
        assertThat(results.get(0).getId()).isNotNull();
    }
}
